services:
  postgres:
    image: postgres:14-alpine
    container_name: autotask-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: autotask_data
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - autotask-network

  autotask-data-sink:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autotask-data-sink
    depends_on:
      postgres:
        condition: service_healthy
    env_file: .env
    environment:
      # Database configuration
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: autotask_data
      PGUSER: postgres
      PGPASSWORD: postgres
      PGSSLMODE: disable
      
      # Sync frequencies (optional)
      SYNC_TICKETS: 15
      SYNC_TIME_ENTRIES: 15
      SYNC_COMPANIES: 1440
      SYNC_CONTACTS: 1440
      
      # Logging configuration
      LOG_LEVEL: debug
      LOG_FORMAT: json
    restart: unless-stopped
    networks:
      - autotask-network

  grafana:
    image: grafana/grafana:latest
    container_name: autotask-grafana
    depends_on:
      - postgres
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - grafana_data:/var/lib/grafana
      - ./dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - autotask-network

networks:
  autotask-network:
    driver: bridge

volumes:
  postgres_data:
  grafana_data: